### ISSUE TITLE
autoload.php

### ISSUE THREAD

**Issue by cyberavm** [Nexmo/nexmo-php#110] opened 2018-07-04 13:19 UTC
Hi!!!! 

I can´t see the autoload.php

Can you help me please

**Comment by lornajane** [comment] 2018-07-04 13:56
At the installation step, what happened when you ran `composer require nexmo/client`?  This should create the `vendor/` folder and put the `autoload.php` but if it didn't, can you show the output of that command please?  This should help us understand what has gone wrong.

**Comment by cyberavm** [comment] 2018-07-04 14:02
Looks this please:

 

root@vps446118:/var/www/vhosts/eclassified.info/httpdocs/vendor/nexmo-php-master# composer require nexmo/client

Do not run Composer as root/super user! See https://getcomposer.org/root for details

Using version ^0.4.0 for nexmo/client

./composer.json has been updated

Loading composer repositories with package information

Updating dependencies (including require-dev)

Your requirements could not be resolved to an installable set of packages.

 

  Problem 1

    - The requested package nexmo/client No version set (parsed as 1.0.0) is satisfiable by nexmo/client[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

  Problem 2

    - This package requires php >=5.6 but your PHP version (5.5.9) does not satisfy that requirement.

  Problem 3

    - phpunit/phpunit 5.7.9 requires php ^5.6 || ^7.0 -> your PHP version (5.5.9) does not satisfy that requirement.

    - phpunit/phpunit 5.7.8 requires php ^5.6 || ^7.0 -> your PHP version (5.5.9) does not satisfy that requirement.

…..

    - phpunit/phpunit 5.3.2 requires php ^5.6 || ^7.0 -> your PHP version (5.5.9) does not satisfy that requirement.

    - phpunit/phpunit 5.3.1 requires php ^5.6 || ^7.0 -> your PHP version (5.5.9) does not satisfy that requirement.

    - phpunit/phpunit 5.3.0 requires php ^5.6 || ^7.0 -> your PHP version (5.5.9) does not satisfy that requirement.

    - Installation request for phpunit/phpunit ^5.3 -> satisfiable by phpunit/phpunit[5.3.0, 5.3.1, 5.3.2, 5.3.3, 5.3.4, 5.3.5, 5.4.0, 5.4.1, 5.4.2, 5.4.3, 5.4.4, 5.4.5, 5.4.6, 5.4.7, 5.4.8, 5.5.0, 5.5.1, 5.5.2, 5.5.3, 5.5.4, 5.5.5, 5.5.6, 5.5.7, 5.6.0, 5.6.1, 5.6.2, 5.6.3, 5.6.4, 5.6.5, 5.6.6, 5.6.7, 5.6.8, 5.7.0, 5.7.1, 5.7.10, 5.7.11, 5.7.12, 5.7.13, 5.7.14, 5.7.15, 5.7.16, 5.7.17, 5.7.18, 5.7.19, 5.7.2, 5.7.20, 5.7.21, 5.7.22, 5.7.23, 5.7.24, 5.7.25, 5.7.26, 5.7.27, 5.7.3, 5.7.4, 5.7.5, 5.7.6, 5.7.7, 5.7.8, 5.7.9].

 

Installation failed, reverting ./composer.json to its original content.

root@vps446118:/var/www/vhosts/eclassified.info/httpdocs/vendor/nexmo-php-master# php -v

PHP 5.5.9-1ubuntu4.22 (cli) (built: Aug  4 2017 19:40:28)

Copyright (c) 1997-2014 The PHP Group

Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies

    with the ionCube PHP Loader v4.6.0, Copyright (c) 2002-2014, by ionCube Ltd., and

    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

root@vps446118:/var/www/vhosts/eclassified.info/httpdocs/vendor/nexmo-php-master#

 

help me, please, 

 

thank you in advance

 

De: Lorna Jane Mitchell <notifications@github.com> 
Enviado el: miércoles, 4 de julio de 2018 14:57
Para: Nexmo/nexmo-php <nexmo-php@noreply.github.com>
CC: cyberavm <alberto.vazquez@axiombit.com>; Author <author@noreply.github.com>
Asunto: Re: [Nexmo/nexmo-php] autoload.php (#110)

 

At the installation step, what happened when you ran composer require nexmo/client? This should create the vendor/ folder and put the autoload.php but if it didn't, can you show the output of that command please? This should help us understand what has gone wrong.

**Comment by lornajane** [comment] 2018-07-04 14:17
Ah, I'm sorry to say that the main problem here is that the library doesn't support older versions of PHP - you have PHP 5.5 and PHP 5.6 is required.  You will need to upgrade your PHP installation in order to make use of this library.

**Comment by cyberavm** [comment] 2018-07-05 07:48
I am finding it very complicated to generate the "vendor" package. It would be good if you already facilitated the product with this generated package. I get many inconveniences. I am not a systems expert. I'm a porgrammer rather. Can not really help me and provide me with the package "vendor" generated?

 



 

De: Lorna Jane Mitchell <notifications@github.com> 
Enviado el: miércoles, 4 de julio de 2018 15:17
Para: Nexmo/nexmo-php <nexmo-php@noreply.github.com>
CC: cyberavm <alberto.vazquez@axiombit.com>; Author <author@noreply.github.com>
Asunto: Re: [Nexmo/nexmo-php] autoload.php (#110)

 

Ah, I'm sorry to say that the main problem here is that the library doesn't support older versions of PHP - you have PHP 5.5 and PHP 5.6 is required. You will need to upgrade your PHP installation in order to make use of this library.

**Comment by lornajane** [comment] 2018-07-05 07:58
Thanks for keeping us posted.  In order to use the library, your platform will need to meet the basic system requirements as stated in the README.  Please upgrade your PHP to PHP 5.6 or later (I'd recommend 7.1 or later, since we will drop support for the old PHP 5 branch later this year).  I will close this issue now but if you upgrade your PHP and have any other questions for us at all, please open another issue and we'll be pleased to help!

**Comment by cyberavm** [comment] 2018-07-05 09:04
Well, it is clear that he does not want to help much, I say, look at the image: I have php 7. And the error is in what you have published.

I hoped he would be more loving and more involved.

 



 

De: Lorna Jane Mitchell <notifications@github.com> 
Enviado el: jueves, 5 de julio de 2018 8:59
Para: Nexmo/nexmo-php <nexmo-php@noreply.github.com>
CC: cyberavm <alberto.vazquez@axiombit.com>; Author <author@noreply.github.com>
Asunto: Re: [Nexmo/nexmo-php] autoload.php (#110)

 

Thanks for keeping us posted. In order to use the library, your platform will need to meet the basic system requirements as stated in the README. Please upgrade your PHP to PHP 5.6 or later (I'd recommend 7.1 or later, since we will drop support for the old PHP 5 branch later this year). I will close this issue now but if you upgrade your PHP and have any other questions for us at all, please open another issue and we'll be pleased to help!

**Comment by lornajane** [comment] 2018-07-05 09:14
It is not clear what the problem is, did you upgrade your PHP?  Because the output you sent above shows PHP 5.5:

From `php -v`
```
PHP 5.5.9-1ubuntu4.22 (cli) (built: Aug  4 2017 19:40:28)
```

Output of `composer`
```
This package requires php >=5.6 but your PHP version (5.5.9) does not satisfy that requirement.
```

If you upgraded, and still have errors, please let us know the current version and any error output that you are observing so we can help further?

**Comment by cyberavm** [comment] 2018-07-05 09:16
No, look the picture please:

 



 

 

 

De: Lorna Jane Mitchell <notifications@github.com> 
Enviado el: jueves, 5 de julio de 2018 10:15
Para: Nexmo/nexmo-php <nexmo-php@noreply.github.com>
CC: cyberavm <alberto.vazquez@axiombit.com>; Author <author@noreply.github.com>
Asunto: Re: [Nexmo/nexmo-php] autoload.php (#110)

 

It is not clear what the problem is, did you upgrade your PHP? Because the output you sent above shows PHP 5.5:

From php -v

PHP 5.5.9-1ubuntu4.22 (cli) (built: Aug  4 2017 19:40:28)

Output of composer

This package requires php >=5.6 but your PHP version (5.5.9) does not satisfy that requirement.

If you upgraded, and still have errors, please let us know the current version and any error output that you are observing so we can help further?

**Comment by lornajane** [comment] 2018-07-05 09:35
Ah, there isn't a picture visible in your comment.  Could you perhaps upload it on the web version of GitHub?

**Comment by cyberavm** [comment] 2018-07-05 09:38
Look please:

 

root@vps484913:~/nexmo-php-master# php -version

PHP 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS )

Copyright (c) 1997-2017 The PHP Group

Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies

    with Zend OPcache v7.0.30-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

root@vps484913:~/nexmo-php-master# composer require nexmo/client

Using version ^1.4 for nexmo/client

./composer.json has been updated

Loading composer repositories with package information

Updating dependencies (including require-dev)

Your requirements could not be resolved to an installable set of packages.

 

  Problem 1

    - The requested package nexmo/client No version set (parsed as 1.0.0) could not be found.

 

Potential causes:

- A typo in the package name

- The package is not available in a stable-enough version according to your minimum-stability setting

   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

 

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

 

Installation failed, reverting ./composer.json to its original content.

root@vps484913:~/nexmo-php-master#

root@vps484913:~/nexmo-php-master#

 

 

And i donwloaded this:

https://github.com/Nexmo/nexmo-php

 

De: Lorna Jane Mitchell <notifications@github.com> 
Enviado el: jueves, 5 de julio de 2018 10:36
Para: Nexmo/nexmo-php <nexmo-php@noreply.github.com>
CC: cyberavm <alberto.vazquez@axiombit.com>; Author <author@noreply.github.com>
Asunto: Re: [Nexmo/nexmo-php] autoload.php (#110)

 

Ah, there isn't a picture visible in your comment. Could you perhaps upload it on the web version of GitHub?

**Comment by lornajane** [comment] 2018-07-05 12:46
Thanks for the extra information, this helps to understand what's happening.  Could you please share with us (as text rather than images):
* the output of `composer --version`
* the contents of your `composer.json` file
* the output of the same require command but with all the debugging turned on: `composer -vvv require nexmo/client`

Hopefully with a bit more info we can understand the problem and offer a bit more advice.

**Comment by cyberavm** [comment] 2018-07-05 13:05
root@vps484913:~/nexmo-php-master# composer --version

Composer version @package_branch_alias_version@ (1.0.0-beta2) 2016-03-27 16:00:34

root@vps484913:~/nexmo-php-master#

 

 

{

  "name": "nexmo/client",

  "description": "PHP Client for using Nexmo's API.",

  "license": "MIT",

  "type": "library",

  "authors": [

    {

      "name": "Tim Lytle",

      "email": "tim@nexmo.com",

      "role": "Developer",

      "homepage": "http://twitter.com/tjlytle"

    }

  ],

  "support": {

    "email": "devrel@nexmo.com"

  },

  "require": {

    "php": ">=5.6",

    "php-http/client-implementation": "^1.0",

    "zendframework/zend-diactoros": "^1.3",

    "php-http/guzzle6-adapter": "^1.0",

    "lcobucci/jwt": "^3.2"

  },

  "require-dev": {

    "phpunit/phpunit": "^5.3",

    "php-http/mock-client": "^0.3.0",

    "estahn/phpunit-json-assertions": "@stable",

    "squizlabs/php_codesniffer": "^3.1"

  },

  "autoload": {

    "psr-4": {

      "Nexmo\\": "src/"

    }

  },

  "autoload-dev": {

    "psr-4": {

      "Nexmo\\": "test/",

      "NexmoTest\\": "test/"

    }

  }

}

 

 

 

 

root@vps484913:~/nexmo-php-master# composer -vvv require nexmo/client >> "nexmo.log"

Reading ./composer.json

Loading config file ./composer.json

Checking CA file /etc/ssl/certs/ca-certificates.crt

Executing command (/root/nexmo-php-master): git branch --no-color --no-abbrev -v

Executing command (/root/nexmo-php-master): git describe --exact-match --tags

Failed to initialize global composer: Composer could not find the config file: /root/.config/composer/composer.json

To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

Downloading https://packagist.org/packages.json

Writing /root/.cache/composer/repo/https---packagist.org/packages.json into cache

Reading /root/.cache/composer/repo/https---packagist.org/p-provider-2013.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/p-provider-2014.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/p-provider-2015.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/p-provider-2016.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/p-provider-2017.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/p-provider-2017-10.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/p-provider-2018-01.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/p-provider-2018-04.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/p-provider-archived.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/p-provider-latest.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-nexmo$client.json from cache

Using version ^1.4 for nexmo/client

./composer.json has been updated

Reading ./composer.json

Loading config file ./composer.json

Executing command (/root/nexmo-php-master): git branch --no-color --no-abbrev -v

Executing command (/root/nexmo-php-master): git describe --exact-match --tags

Failed to initialize global composer: Composer could not find the config file: /root/.config/composer/composer.json

To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

Loading composer repositories with package information

Downloading https://packagist.org/packages.json

Writing /root/.cache/composer/repo/https---packagist.org/packages.json into cache

Updating dependencies (including require-dev)

Reading /root/.cache/composer/repo/https---packagist.org/p-provider-2013.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/p-provider-2014.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/p-provider-2015.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/p-provider-2016.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/p-provider-2017.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/p-provider-2017-10.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/p-provider-2018-01.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/p-provider-2018-04.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/p-provider-archived.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/p-provider-latest.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-nexmo$client.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-php-http$client-implementation.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-zendframework$zend-diactoros.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-psr$http-message.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-php-http$guzzle6-adapter.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-php-http$httplug.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-guzzlehttp$guzzle.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-php-http$promise.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-guzzlehttp$psr7.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-guzzlehttp$promises.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-lcobucci$jwt.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-phpunit$phpunit.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-myclabs$deep-copy.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-phpspec$prophecy.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-phpunit$php-code-coverage.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-phpunit$php-file-iterator.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-phpunit$php-text-template.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-phpunit$php-timer.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-phpunit$phpunit-mock-objects.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-sebastian$comparator.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-sebastian$diff.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-sebastian$environment.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-sebastian$exporter.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-sebastian$global-state.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-sebastian$object-enumerator.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-sebastian$resource-operations.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-sebastian$version.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-symfony$yaml.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-phpdocumentor$reflection-docblock.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-doctrine$instantiator.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-sebastian$recursion-context.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-phpunit$php-token-stream.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-sebastian$code-unit-reverse-lookup.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-symfony$polyfill-ctype.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-dflydev$markdown.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-phpdocumentor$reflection-common.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-phpdocumentor$type-resolver.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-webmozart$assert.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-php-http$mock-client.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-php-http$client-common.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-php-http$discovery.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-php-http$message-factory.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-php-http$message.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-symfony$options-resolver.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-clue$stream-filter.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-estahn$phpunit-json-assertions.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-justinrainbow$json-schema.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-mtdowling$jmespath.php.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-squizlabs$php-codesniffer.json from cache

Reading /root/.cache/composer/repo/https---packagist.org/provider-symfony$console.json from cache

Resolving dependencies through SAT

Dependency resolution completed in 0.414 seconds

Your requirements could not be resolved to an installable set of packages.

 

  Problem 1

    - The requested package nexmo/client No version set (parsed as 1.0.0) could not be found.

 

Potential causes:

- A typo in the package name

- The package is not available in a stable-enough version according to your minimum-stability setting

   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

 

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

 

Installation failed, reverting ./composer.json to its original content.

root@vps484913:~/nexmo-php-master#

 

 

 

De: Lorna Jane Mitchell <notifications@github.com> 
Enviado el: jueves, 5 de julio de 2018 13:47
Para: Nexmo/nexmo-php <nexmo-php@noreply.github.com>
CC: cyberavm <alberto.vazquez@axiombit.com>; Author <author@noreply.github.com>
Asunto: Re: [Nexmo/nexmo-php] autoload.php (#110)

 

Thanks for the extra information, this helps to understand what's happening. Could you please share with us (as text rather than images):

*	the output of composer --version
*	the contents of your composer.json file
*	the output of the same require command but with all the debugging turned on: composer -vvv require nexmo/client

Hopefully with a bit more info we can understand the problem and offer a bit more advice.

**Comment by lornajane** [comment] 2018-07-05 13:29
Thanks! I think what is happening here is that you are running the install command inside a copy of this repository.  The library is something that you add to your own project, so the `composer require nexmo/client` command should be run inside your own project, not inside a copy of this one.  Does that help?

**Comment by cyberavm** [comment] 2018-07-05 19:12
problem solved!!

 

thank you very much

 

De: Lorna Jane Mitchell <notifications@github.com> 
Enviado el: jueves, 5 de julio de 2018 14:29
Para: Nexmo/nexmo-php <nexmo-php@noreply.github.com>
CC: cyberavm <alberto.vazquez@axiombit.com>; Author <author@noreply.github.com>
Asunto: Re: [Nexmo/nexmo-php] autoload.php (#110)

 

Thanks! I think what is happening here is that you are running the install command inside a copy of this repository. The library is something that you add to your own project, so the composer require nexmo/client command should be run inside your own project, not inside a copy of this one. Does that help?

**Closed** 2018-07-05 19:42 UTC
